### ISSUE TITLE
I can not inference with my model !

### ISSUE THREAD

**Issue by AmirAzz** [roboflow/zero-shot-object-tracking#33]
Thanks for this video , I tried to use this code : 

!python clip_object_tracker.py --source /content/zero-shot-object-tracking/data/video/Turkey.mp4 --url https://detect.roboflow.com/video-track/2 --api_key ***********  --info  

but this issue appears: 

video 1/1 (23/1351) /content/zero-shot-object-tracking/data/video/Turkey.mp4: 
[Detections]
[Tracks] 2
Traceback (most recent call last):
  File "clip_object_tracker.py", line 370, in <module>
    detect()
  File "clip_object_tracker.py", line 269, in detect
    update_tracks(tracker, frame_count, save_txt, txt_path, save_img, view_img, im0, gn)
  File "clip_object_tracker.py", line 46, in update_tracks
    class_name = names[int(class_num)] if opt.detection_engine == "yolov5" or "yolov7" else class_num
ValueError: invalid literal for int() with base 10: 'damage

**Comment by kjohnabbott** [comment]
I am also having the same issue with a Roboflow model I'm using. Here is my traceback that is similar:

video 1/1 (3/1122) /content/Copy of 20210812_SharkOutsideLineUP.mp4: 
[Detections]
[Tracks] 12
Traceback (most recent call last):
  File "/content/zero-shot-object-tracking/clip_object_tracker.py", line 370, in <module>
    detect()
  File "/content/zero-shot-object-tracking/clip_object_tracker.py", line 269, in detect
    update_tracks(tracker, frame_count, save_txt, txt_path, save_img, view_img, im0, gn)
  File "/content/zero-shot-object-tracking/clip_object_tracker.py", line 46, in update_tracks
    class_name = names[int(class_num)] if opt.detection_engine == "yolov5" or "yolov7" else class_num
ValueError: invalid literal for int() with base 10: 'shark'


it appears I'm getting this error only at the 3rd frame of the video, though.

**Comment by roytravel** [comment]
It will work well if you change the code as below @AmirAzz , @kjohnabbott 

if opt.detection_engine == "yolov5" or opt.detection_engine == "yolov7":
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;class_name = names[int(class_num)]
else:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;class_name = class_num
